### ISSUE TITLE
server端启动报错

### ISSUE THREAD

**Issue by jpfss** [kingston-csj/mmorpg#6]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configResourceRegistry' defined in file [G:\WORK\JavaProgramming\GameProjects\mmorpg\out\production\classes\com\kingston\mmorpg\game\database\config\ConfigResourceRegistry.class]: Initialization of bean failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Null value was assigned to a property [class com.kingston.mmorpg.game.database.config.domain.ConfigSkill.needLevel] of primitive type setter of com.kingston.mmorpg.game.database.config.domain.ConfigSkill.needLevel; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property [class com.kingston.mmorpg.game.database.config.domain.ConfigSkill.needLevel] of primitive type setter of com.kingston.mmorpg.game.database.config.domain.ConfigSkill.needLevel

**Comment by kingston-csj** [comment]
更新下最新的测试数据看下。

**Comment by jpfss** [comment]
更新后试了一下服务端可以启动了，客户端启动报错如下：
2783 [nioEventLoopGroup-2-1] ERROR EXCEPTION - 读取消息出错,模块号102，类型1,异常{} 
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at com.kingston.mmorpg.framework.net.socket.serializer.Serializer.getSerializer(Serializer.java:57)
	at com.kingston.mmorpg.framework.net.socket.codec.PacketEncoder._encode(PacketEncoder.java:45)
	at com.kingston.mmorpg.framework.net.socket.codec.PacketEncoder.encode(PacketEncoder.java:23)
	at com.kingston.mmorpg.framework.net.socket.codec.PacketEncoder.encode(PacketEncoder.java:15)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
	at com.kingston.mmorpg.client.IoSession.sendPacket(IoSession.java:34)
	at com.kingston.mmorpg.client.net.SessionManager.sendMessage(SessionManager.java:21)
	at com.kingston.mmorpg.client.net.ClientTransportHandler.channelActive(ClientTransportHandler.java:25)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:194)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:194)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:758)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:258)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:288)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kingston-csj** [comment]
本地重现不了，你自己debug一下哈

**Comment by jpfss** [comment]
嗯嗯，好的，谢谢
